"""wave 4 data model: indexes, idempotency, per-category positions, checks

Revision ID: 07266c100dff
Revises: e604dc58fa04
Create Date: 2026-08-13 05:15:43.483469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07266c100dff'
down_revision: Union[str, Sequence[str], None] = 'e604dc58fa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key')
    )
    op.drop_constraint(op.f('ai_sessions_created_by_fkey'), 'ai_sessions', type_='foreignkey')
    op.create_foreign_key('ai_sessions_created_by_fkey', 'ai_sessions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_dependencies_project_id'), 'dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_dependencies_to_task_id'), 'dependencies', ['to_task_id'], unique=False)
    op.drop_constraint(op.f('plan_versions_approved_by_fkey'), 'plan_versions', type_='foreignkey')
    op.create_foreign_key('plan_versions_approved_by_fkey', 'plan_versions', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_revisions_op_gin', 'revisions', ['op'], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('revisions_actor_user_id_fkey'), 'revisions', type_='foreignkey')
    op.create_foreign_key('revisions_actor_user_id_fkey', 'revisions', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_assignees_user_id'), 'task_assignees', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_category_id'), 'tasks', ['category_id'], unique=False)
    # Positions are renumbered within each category following the previous order
    # (position, id): the previous numbering ran across the whole project, and
    # "the row's number within its own category" does not follow from it.
    op.execute(
        """
        UPDATE tasks SET position = numbered.rn - 1
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY category_id ORDER BY position, id
            ) AS rn
            FROM tasks
        ) AS numbered
        WHERE tasks.id = numbered.id
        """
    )
    op.create_unique_constraint('uq_tasks_category_position', 'tasks', ['category_id', 'position'], deferrable=True, initially='DEFERRED')
    op.create_check_constraint('ck_tasks_criticality', 'tasks', "criticality IN ('low', 'normal', 'high', 'critical')")
    op.create_check_constraint('ck_tasks_duration_days', 'tasks', 'duration_days >= 1')
    op.create_check_constraint('ck_tasks_progress_pct', 'tasks', 'progress_pct BETWEEN 0 AND 100')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tasks_progress_pct', 'tasks', type_='check')
    op.drop_constraint('ck_tasks_duration_days', 'tasks', type_='check')
    op.drop_constraint('ck_tasks_criticality', 'tasks', type_='check')
    op.drop_constraint('uq_tasks_category_position', 'tasks', type_='unique')
    op.drop_index(op.f('ix_tasks_category_id'), table_name='tasks')
    op.drop_index(op.f('ix_task_assignees_user_id'), table_name='task_assignees')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_constraint('revisions_actor_user_id_fkey', 'revisions', type_='foreignkey')
    op.create_foreign_key(op.f('revisions_actor_user_id_fkey'), 'revisions', 'users', ['actor_user_id'], ['id'])
    op.drop_index('ix_revisions_op_gin', table_name='revisions', postgresql_using='gin')
    op.drop_constraint('plan_versions_approved_by_fkey', 'plan_versions', type_='foreignkey')
    op.create_foreign_key(op.f('plan_versions_approved_by_fkey'), 'plan_versions', 'users', ['approved_by'], ['id'])
    op.drop_index(op.f('ix_dependencies_to_task_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_project_id'), table_name='dependencies')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_constraint('ai_sessions_created_by_fkey', 'ai_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_sessions_created_by_fkey'), 'ai_sessions', 'users', ['created_by'], ['id'])
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
