"""jsonb for the revision journal, indexes on hot foreign keys, role check

revisions.op/inverse used to be json — raw text with no containment operators and
no way to build a GIN index, even though all three features built on this journal
search by content. The product is Postgres-only; after production entries appear,
such an edit costs a rewrite of the table.

The indexes cover the foreign keys that are read constantly: memberships.user_id
(on every request with a session; the composite (org_id, user_id) does not lead
with the right column), tasks.project_id and categories.project_id (reading a
whole project), revisions.batch_id (undoing a group operation).

A CHECK on memberships.role: the column was a free String(16), and a value
outside Role turned into a ValueError — that is, a 500 — before permissions were
even checked.

Revision ID: 3b3648273b7a
Revises: da03b89192b8
Create Date: 2026-08-10 22:02:49.913585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b3648273b7a'
down_revision: Union[str, Sequence[str], None] = 'da03b89192b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_project_id'), 'categories', ['project_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_check_constraint('ck_memberships_role', 'memberships', "role IN ('owner', 'editor', 'viewer', 'client')")
    op.alter_column('revisions', 'op',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('revisions', 'inverse',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_revisions_batch_id'), 'revisions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_revisions_batch_id'), table_name='revisions')
    op.alter_column('revisions', 'inverse',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('revisions', 'op',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('ck_memberships_role', 'memberships', type_='check')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_categories_project_id'), table_name='categories')
    # ### end Alembic commands ###
