"""email verification tokens

The table of single-use address confirmation links: the users.email_verified_at
column existed from the very beginning, but there was nothing to fill it with —
there was no confirmation logic at all.

Arranged like sessions: the plain token goes outward while its hash lies here.
ondelete=CASCADE — deleting a user carries away their unused links; the index on
user_id is needed by confirmation and by resending, both of which look up by owner.

Revision ID: 4d44f75a2766
Revises: 822f5eb3ea88
Create Date: 2026-08-11 07:51:28.915545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d44f75a2766'
down_revision: Union[str, Sequence[str], None] = '822f5eb3ea88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
