"""invitations, project access, active organization on the session

Invitations: the single-use token lies as a hash (like a password and like a
session), hence the uniqueness on token_hash rather than on the address — one
address in an organization may go through any number of links, and the old ones
stay in the table as the record of who invited whom. An index on org_id: the list
of invitations is asked for by the members screen, that is, always by organization.

project_access — individually granted access to a project for the client role.
Indexes on both sides: user_id assembles such a person's project list, project_id
checks the right to a particular project.

sessions.active_org_id — the organization chosen by the switcher. It lives on the
session rather than on the user: one tab looks at one's own company while another
looks at someone else's. SET NULL, so that a deleted organization does not carry
the session away with it.

Revision ID: 822f5eb3ea88
Revises: 3b3648273b7a
Create Date: 2026-08-11 07:35:59.079362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822f5eb3ea88'
down_revision: Union[str, Sequence[str], None] = '3b3648273b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('project_ids', sa.JSON(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer', 'client')", name='ck_invitations_role'),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invitations_org_id'), 'invitations', ['org_id'], unique=False)
    op.create_table('project_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_index(op.f('ix_project_access_project_id'), 'project_access', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_access_user_id'), 'project_access', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('active_org_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_sessions_active_org_id', 'sessions', 'organizations', ['active_org_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_active_org_id', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'active_org_id')
    op.drop_index(op.f('ix_project_access_user_id'), table_name='project_access')
    op.drop_index(op.f('ix_project_access_project_id'), table_name='project_access')
    op.drop_table('project_access')
    op.drop_index(op.f('ix_invitations_org_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
