"""share links, comments, per-project access for the client role

Three tables of public access (section 7 of the specification).

share_links stores the token in plain text, unlike invitations: the owner copies a
public link from the project's settings again and again, and a server that had
forgotten it would leave issuing a new link as the only way to "show it again". A
partial unique index holds the invariant "a project has one link in force"; there
may be any number of revoked ones — that is the record of which address died when.

comments: the author is either a member or a guest by name, and exactly one of the
two. That is held by a CHECK rather than by a route: there are already two routes
that create a comment.

project_access is not here: the same table — with the same columns and indexes —
was already created by the invitations migration (822f5eb3ea88), and this revision
lands after it.

Revision ID: adee83e4d023
Revises: 4d44f75a2766
Create Date: 2026-08-11 07:54:59.465600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adee83e4d023'
down_revision: Union[str, Sequence[str], None] = '4d44f75a2766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('comments_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_share_links_project_id'), 'share_links', ['project_id'], unique=False)
    op.create_index('uq_share_links_active_project', 'share_links', ['project_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    # clock_timestamp(), not now(): the order of remarks rests on this timestamp,
    # while now() returns the same time for every insert in one transaction.
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(author_user_id, guest_name) = 1', name='ck_comments_single_author'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index('uq_share_links_active_project', table_name='share_links', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_share_links_project_id'), table_name='share_links')
    op.drop_table('share_links')
    # ### end Alembic commands ###
